### ISSUE TITLE
NetCDF triangular grid

### ISSUE THREAD

**Issue by bobsurf00** [NOAA-ORR-ERD/PyGnome#59]
Hi,
I'm trying to customise PyGnome using current data derived from a finite element hydrodynamic model.  Doing my best to follow the example script provided for Columbia River and the data formats technical documentation but I'm getting the following error.
![image](https://user-images.githubusercontent.com/45707327/89506797-36d7d180-d7fe-11ea-9aa2-a43655594b24.png)

I attach my script, bna and netcdf files.  
[script_mermaid2.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/5033429/script_mermaid2.zip)
Anyone have any ideas what could be going wrong? Pretty sure its something to do with reading in the boundary nodes.
Much appreciated 
Rob

**Comment by jay-hennen** [comment]
Hi Rob,

TimeGridVelTri_c is a component of the GridCurrentMover, which is basically deprecated at this point (though not officially).

What you want to use instead are the gnome.environment.environment_objects.GridCurrent and gnome.movers.PyCurrentMover objects. Judging by the header in your netCDF file, it should work with zero special work.
```
current = GridCurrent.from_netCDF(filename="NWS.nc")
mover = PyCurrentMover(current=current)
```
If you have further questions let me know.

**Comment by bobsurf00** [comment]
Thanks for your reply Jay.

Had a go at this but now get the following error:

![image](https://user-images.githubusercontent.com/45707327/89701380-f6489700-d968-11ea-83f8-ae62d2f9b837.png)

My script is attached
[script_mermaid3.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/5044571/script_mermaid3.zip)

**Comment by bobsurf00** [comment]
Please ignore previous comment - times were incorrect in my netcdf file.  

I've corrected and it appears to be successfully reading in now....however....this is the next error that has got me stumped.  Hopefully this means something to you.  
Thanks


![image](https://user-images.githubusercontent.com/45707327/89702752-0cf5ea80-d977-11ea-9f39-a460e992b5b1.png)

**Comment by jay-hennen** [comment]
What version of gridded are you using? And is that actually an error? A traceback would be useful

**Comment by bobsurf00** [comment]
Sorry Jay, I'm not sure what version of gridded I'm using - how do I tell?
Maybe something else wrong with my netcdf file.  
The above was all I received as a traceback - are there any other diagnostics I can provide?  
Thanks
Rob

**Comment by ChrisBarker-NOAA** [comment]
Two ways to tell your version:

`$ conda list`

and then look for gridded.

I've got:

`gridded                   0.2.5                    py27_0    conda-forge`

or python:

```
$ python -c "import gridded; print(gridded.__version__)"
0.2.4
```
@jay-hennen: oops, it looks like we may have not incremented __version__ !

**Comment by bobsurf00** [comment]
Hi Jay - I have the same as you.

$ conda list 

![image](https://user-images.githubusercontent.com/45707327/89854184-d1049480-dbc5-11ea-8a30-9c6388629ade.png)
 and 

![image](https://user-images.githubusercontent.com/45707327/89854221-ea0d4580-dbc5-11ea-8f5c-54c4f383d6d8.png)

**Comment by jay-hennen** [comment]
There doesn't seem to be an error. I can't run your provided script because of the broken time data.

Can you do some double checking? Try running the model without the unstructured grid to determine if it's actually the cause of the problem, and then narrow it down from there.

**Comment by bobsurf00** [comment]
Hi Jay - the model runs fine without the unstructured grid.  I tried it with just wind and then with the Hycom data.  So I guess there must be something wrong with my NWS netcdf file.

I fixed the broken time data we discussed previously however it now seems to base the data to 1975 despite the fact that the netcdf file bases it at 2015.  Maybe that's the problem. 

![image](https://user-images.githubusercontent.com/45707327/90020239-28982280-dce2-11ea-9bbb-ea299e8caadb.png)

So it reads the day and the month correctly but not the year. Is there a way of checking the netcdf file?  

I'm also not 100% sure on the nbe and nv variables.  Does pygnome use these?

Files attached if you have time to look at them.

Thanks

Rob

[script_mermaid4.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/5063003/script_mermaid4.zip)

**Comment by bobsurf00** [comment]
hi @jay-hennen just wondering if you have any suggestions on this issue - tks

**Comment by jay-hennen** [comment]
It looks like something in the file is still broken. It doesn't crash with a python error, the process just dies altogether. It also looks like it breaks during a file read operation, which suggests that something in the C foundation of netCDF4 is breaking. (that's what the variable[slices] line is doing, in essence; it should be the first time the data is actually being loaded)

**Comment by bobsurf00** [comment]
Hi @jay-hennen - looks like I created the tidal current netCDF file in classic format, which probably explains the failure. 

I've recreated the file in NetCDF4 (attached), however, it's giving the error below.  For some reason it thinks that the times of the currents are based to 09/24/**75** 04:00:00 when they are actually 09/25/15 03:00.  
[script_mermaid5.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/5103207/script_mermaid5.zip)

![image](https://user-images.githubusercontent.com/45707327/90773018-e6955f00-e327-11ea-847d-d069a5be3612.png)

![image](https://user-images.githubusercontent.com/45707327/90773349-54418b00-e328-11ea-8d30-954966a6965f.png)

If you have any ideas, I'd be grateful.
Thanks
Rob

**Comment by jay-hennen** [comment]
`ValueError: time specified (09/24/15 03:00:00) is not within the bounds of the time (09/24/15 04:00:00 to 09/26/15 04:00:00)`

That's what I got when I ran your script.

Could you provide your netCDF4 version and cftime version? I'm not sure where else to go here. You might want to add in a line in the setup as follows, just to print the time range out as soon as the current object is created:
```
print current.time.min_time
print current.time.max_time
```
